### ISSUE TITLE
Inconsistent section references in revision history

### ISSUE THREAD

**Issue by rhattersley** [cf-metadata/cf-conventions#13]
[Appendix G, Revision History](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.6/build/cf-conventions.html#revhistory) contains two different styles of section reference:

> Section 3.5, "Flags"

and

> the section called "Azimuthal equidistant"

Do we care about preserving this difference? Would it be OK if all the section references followed the first style, as elsewhere in the document?

**Comment by davidhassell** [comment]
Hi Richard,

I favour keeping the inconsistencies as they are for the 1.6 document. This will, in general, make checking the veracity easier. If there is a will to tidy this up in the future (e.g. for 1.7) then it can go in as a defect ticket in the usual fashion.

Thanks,
David

**Comment by rhattersley** [comment]
The ability to use explicit/custom link text has been [added to asciidoctor master](https://github.com/asciidoctor/asciidoctor/issues/1468).
