### ISSUE TITLE
Checking Chapter 1

### ISSUE THREAD

**Issue by davidhassell** [cf-metadata/cf-conventions#2]
I'm currently checking the asciidoc version of chapter 1. Progress, as it happens, at  https://github.com/davidhassell/cf-conventions/tree/chapter1

**Comment by davidhassell** [comment]
Largely ok. I have a couple of technical questions for Richard, which will apply to all of the other sections.

* The text is ok
* The references appear to resolve correctly (which will need checking when the entire document is built)
* The section names are ok, but there are no section numbers. Richard - do I have to worry about this, or are these generated when the entire document is put together?
* There is no table of contents at the top of the chapter. Richard - do I have to worry about this, or are these generated when the entire document is put together?

Thanks,
David

**Comment by rhattersley** [comment]
> The references appear to resolve correctly (which will need checking when the entire document is built)

You can them here: http://cf-metadata.github.io/

> The section names are ok, but there are no section numbers. Richard - do I have to worry about this, or are these generated when the entire document is put together?

Section numbers are added automatically, see http://cf-metadata.github.io/#_introduction

> There is no table of contents at the top of the chapter.

I don't know of a simple, automatic way to do that right now. If it's really important for us I'll chase it up on the AsciiDoctor discussion forum.

**Comment by davidhassell** [comment]
Thanks, Richard - that's all good.

I'll ignore the table of contents for now.

Chapter 1 is fine, I think. No need for pull request. 

I'm starting to look at chapter 2, now.

All the best,

David

**Comment by rhattersley** [comment]
> There is no table of contents at the top of the chapter.

I'll make a separate issue for this.

**Comment by rhattersley** [comment]
> Chapter 1 is fine, I think. No need for pull request.

Super. Thanks @davidhassell. I'll close this and let the somewhat open questions be tracked by other issues.
