### ISSUE TITLE
Per-chapter table of contents

### ISSUE THREAD

**Issue by rhattersley** [cf-metadata/cf-conventions#4]
As mentioned in #2, "There is no table of contents at the top of the chapter."

**Comment by rhattersley** [comment]
1. There doesn't seem to be an automatic way to generate these with asciidoctor.
2. The [existing PDF version](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.6/build/cf-conventions.pdf) doesn't have per-chapter table of contents either.

@JonathanGregory / @davidhassell Are we happy to leave out the per-chapter table of contents for _all_ versions built with asciidoctor?

**Comment by JonathanGregory** [comment]
Yes, I would be happy to leave them out. So long as we have an overall table of contents, I don't think the per-chapter ones are important to have. Thanks. Jonathan

**Comment by rhattersley** [comment]
Super, thanks @JonathanGregory.
