### ISSUE TITLE
PDF output

### ISSUE THREAD

**Issue by rhattersley** [cf-metadata/cf-conventions#48]
See https://github.com/cf-metadata/cf-conventions/pull/45#issuecomment-159609859

**Comment by marqh** [comment]
I think this is done now
http://cf-metadata.github.io/cf-conventions.pdf

**Comment by marqh** [comment]
this is the last open issue in 
https://github.com/cf-metadata/cf-conventions/milestones/1.6
i wonder if our goalposts are still minded to grow legs
:smirk:

**Comment by rhattersley** [comment]
I believe @JonathanGregory is intending to review the PDF output as well, so I'd like to hold fire for now.

**Comment by JonathanGregory** [comment]
Yes, I am going to review it. Thanks. I can't justify that much paper so I will look at the two PDFs adjacently online. Jonathan

**Comment by marqh** [comment]
I believe that all active pull requests in the 1.6 milestone are now closed.

It is my view that this issue is now resolved.

@rhattersley @JonathanGregory 
do you have any reasons to keep this ticket open, or may I close it?

Would you like to include any deployment tickets in the 1.6 milestone or may we also conclude that as achieved?

thank you
mark

**Comment by JonathanGregory** [comment]
How marvellous. Well done on this remarkable achievement.

If it's now ready to go live, as HTML and PDF, I think we should just check with someone first. Shall I ask Karl if that's OK?

Jonathan

**Comment by rhattersley** [comment]
> Shall I ask Karl if that's OK?

That sounds like a super plan. :grinning:

**Comment by rhattersley** [comment]
For the record, Karl is on-board, but has also requested Jeff's opinion.

**Comment by rhattersley** [comment]
Since the remaining room for debate seems to be more about "how do we make v1.7 from here?", rather than any issues with the current version, I've tagged [v1.6](https://github.com/cf-metadata/cf-conventions/releases/tag/v1.6.0). :grinning:

It seems fair to close this issue now. It's easy to open new ones!
